const express = require('express')
const { userCreation,userLogin, logout, sendEmail, VerifyOtp, emailValidator } = require('../controllers/athentication_authorisation')
const { LoginAuthenticator } = require('../middlewares/auth')
const {addToCart, getCart, removeFromCart, quantity, addAddress, getUser, editUser} = require('../controllers/user')
const { getProducts, fetchProduct } = require('../controllers/admin')
const { addOrder, getUserOrder, updateOrder } = require('../controllers/orders')
const router = express.Router()

router.post('/addToCart/:id',LoginAuthenticator,addToCart)
router.get('/getCart/:id',LoginAuthenticator,getCart)
router.delete('/delfromCart/:id/:index',LoginAuthenticator,removeFromCart)
router.post('/quantity/:id',LoginAuthenticator,quantity)
router.post('/checkout/:id',LoginAuthenticator,addAddress)
router.get('/getUser/:id',LoginAuthenticator,getUser)
router.post('/add-order/:id',LoginAuthenticator,addOrder)
router.get('/product/:id',LoginAuthenticator,fetchProduct)
router.post('/editUser/:id',LoginAuthenticator,editUser)
router.put('/updateOrder/:id',updateOrder)
router.get('/myOrders/:id',LoginAuthenticator,getUserOrder)

router.get('/',getProducts)
router.post('/emailverify',emailValidator)
router.post('/sendmail',sendEmail)
router.post('/verifyotp',VerifyOtp)
router.post('/signUp',userCreation)
router.post('/login',userLogin)
router.get('/logout',logout)

module.exports = router